export const FETCH_TOURNAMENTS = 'FETCH_TOURNAMENTS';
export const FETCH_TOURNAMENTS_START = 'FETCH_TOURNAMENTS_START';
export const FETCH_TOURNAMENTS_SUCCESS = 'FETCH_TOURNAMENTS_SUCCESS';
export const FETCH_TOURNAMENTS_FAIL = 'FETCH_TOURNAMENTS_FAIL';

export const ADD_TOURNAMENT_SUCCESS = 'ADD_TOURNAMENT_SUCCESS';
export const ADD_TOURNAMENT_FAIL = 'ADD_TOURNAMENT_FAIL';

export const DELETE_TOURNAMENT_SUCCESS = 'DELETE_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_FAIL = 'DELETE_TOURNAMENT_FAIL';

export const EDIT_TOURNAMENT_SUCCESS = 'EDIT_TOURNAMENT_SUCCESS';
export const EDIT_TOURNAMENT_FAIL = 'EDIT_TOURNAMENT_FAIL';

export const SEARCH_TOURNAMENT_START = 'SEARCH_TOURNAMENT_START';
export const SEARCH_TOURNAMENT_SUCCESS = 'SEARCH_TOURNAMENT_SUCCESS';
export const SEARCH_TOURNAMENT_FAIL = 'SEARCH_TOURNAMENT_FAIL';
